env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:css-modules/recommended'
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - css-modules
rules: {}
parser: "babel-eslint"
settings:
  react:
    pragma: React
    version: 16.8.6
